### PR TITLE
Use native fetch instead of node-fetch

### PR DESCRIPTION
**Pull request by numselli**

### CODE REVIEW

**Comment by meister03** [comment]
but this comes at sake of not supporting node <= 18 below. I will have to check if its okay....

**Comment by NotDemonix** [comment]
Just make people update, why can't they?

**Comment by NotDemonix** [comment]
They can always use the older version too

**Comment by numselli** [comment]
Alternatively updating node-fetch should work. The big benifit of using native fetch is that it would make this package have 0 dependencies.

**Comment by NotDemonix** [comment]
> Alternatively updating node-fetch should work. The big benifit of using native fetch is that it would make this package have 0 dependencies.

But still, is there anyone that keeps updating their packages and not nodejs version? I don't think so

**Comment by meister03** [comment]
Used the native https package instead, @numselli / @NotDemonix  could you give it a try? (2.1.5)

**Comment by NotDemonix** [comment]
I can on Friday at earliest

**Comment by eliyya** [comment]
and isn't there a possibility to add it as a polyfill and place `node-fetch` as an optional dependency?
something like...
```js
global.fetch ??= require('node-fetch')
```

**Comment by meister03** [comment]
> and isn't there a possibility to add it as a polyfill and place `node-fetch` as an optional dependency? something like...
> 
> ```js
> global.fetch ??= require('node-fetch')
> ```
Not required anymore, since we are using the native https package.

**Comment by meister03** [comment]
> > and isn't there a possibility to add it as a polyfill and place `node-fetch` as an optional dependency? something like...
> > ```js
> > global.fetch ??= require('node-fetch')
> > ```
> 
> Not required anymore, since we are using the native https package.

**Pull request closed without merging**
